# Generated by Django 6.1 on 2026-08-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_category', models.CharField(max_length=100)),
                ('planting_season', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=150)),
                ('planting_advice', models.TextField()),
                ('fertilizer_advice', models.TextField()),
                ('pest_information', models.TextField()),
                ('disease_information', models.TextField()),
                ('harvesting_advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
