# Generated by Django 6.1 on 2026-08-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropadvisory',
            options={'verbose_name': 'Crop Advisory', 'verbose_name_plural': 'Crop Advisories'},
        ),
    ]
