# Generated by Django 6.1 on 2026-08-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0002_alter_cropadvisory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('problem_name', models.CharField(max_length=150)),
                ('problem_type', models.CharField(max_length=50)),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('prevention', models.TextField()),
                ('control_measures', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pest/Disease Advisory',
                'verbose_name_plural': 'Pest/Disease Advisories',
            },
        ),
    ]
