# Generated by Django 6.1 on 2026-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0004_farmingtip'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('animal_category', models.CharField(max_length=100)),
                ('feeding_advice', models.TextField()),
                ('housing_advice', models.TextField()),
                ('common_diseases', models.TextField()),
                ('disease_prevention', models.TextField()),
                ('management_advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
