# Generated by Django 6.1 on 2026-08-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0005_livestockadvisory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Farmer Feedback',
                'verbose_name_plural': 'Farmer Feedback',
            },
        ),
        migrations.AlterModelOptions(
            name='livestockadvisory',
            options={'verbose_name': 'Livestock Advisory', 'verbose_name_plural': 'Livestock Advisories'},
        ),
    ]
